# Generated by Django 4.1 on 2022-09-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
