# Generated by Django 4.1 on 2022-09-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_delete_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='price',
            new_name='star',
        ),
    ]
